apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor-container-webhook.fullname" . }}
  labels:
    {{- include "harbor-container-webhook.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  webhook-config.yaml: |
    port: {{ .Values.service.port }}
    {{- if .Values.certManager.enabled }}
    certDir: "/etc/hcw/certs"
    {{- else }}
    certDir: "{{ .Values.certDir }}"
    {{- end }}
    metricsAddr: ":{{ .Values.prometheus.port }}"
    healthAddr: ":{{ .Values.healthPort }}"
    verbose: {{ .Values.verbose }}
    rules:
    {{- concat (default list .Values.rules) (default list .Values.extraRules) | toYaml | nindent 6 }}
